# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CmcPre < Formula
  desc "CMC PRE-RELEASES - A command line tool to help you write Conventional Commits"
  homepage "https://github.com/marcdonald/cmc-cli"
  version "0.0.1-alpha8"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/MarcDonald/cmc-cli/releases/download/0.0.1-alpha8/cmc_Darwin_x86_64.tar.gz"
      sha256 "4ad2a2bf90007c3f71674a79dc2ff0fa3ab592ee1253fc078144c06f3b689434"

      def install
        bin.install "cmc"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/MarcDonald/cmc-cli/releases/download/0.0.1-alpha8/cmc_Darwin_arm64.tar.gz"
      sha256 "a5fafdc39d488ac8e609dcbcbc477189b0cb825421b2e5b70a2d00f235c9340a"

      def install
        bin.install "cmc"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/MarcDonald/cmc-cli/releases/download/0.0.1-alpha8/cmc_Linux_x86_64.tar.gz"
      sha256 "d5bc2df91c398d9505ca7f088a7a86d604d7e0f61513222260b04467d95c23c3"

      def install
        bin.install "cmc"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/MarcDonald/cmc-cli/releases/download/0.0.1-alpha8/cmc_Linux_arm64.tar.gz"
      sha256 "ee3231a2666024f4cb4222da070a49a824b1fd23bbca9b64ecbb491b5ff24923"

      def install
        bin.install "cmc"
      end
    end
  end
end
