# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CmmiterPre < Formula
  desc "CMMITER PRE-RELEASES - A command line tool to help you write Conventional Commits"
  homepage "https://github.com/marcdonald/cmmiter"
  version "1.0.0-beta1"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/MarcDonald/cmmiter/releases/download/1.0.0-beta1/cmmiter_Darwin_arm64.tar.gz"
      sha256 "a68d4beeb2192bb804b2c41ee5440d72497b1a76cd94ebcf72b3375444d46b5f"

      def install
        bin.install "cmt"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/MarcDonald/cmmiter/releases/download/1.0.0-beta1/cmmiter_Darwin_x86_64.tar.gz"
      sha256 "d160dac950430a89fd46d13be185533d1bd1ada327598256645b2e574e0bb5c3"

      def install
        bin.install "cmt"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/MarcDonald/cmmiter/releases/download/1.0.0-beta1/cmmiter_Linux_x86_64.tar.gz"
      sha256 "07f77472ba5e64eda7aa559b0d84beda0413a95851adc5e451df22a52dfd41ef"

      def install
        bin.install "cmt"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/MarcDonald/cmmiter/releases/download/1.0.0-beta1/cmmiter_Linux_arm64.tar.gz"
      sha256 "cff82045abc408b7660a2dd8f91d55fd5ecf5e2e120fb6c2c5d7d9a10cca8fb5"

      def install
        bin.install "cmt"
      end
    end
  end
end
